name: Setup sccache
description: Install and configure sccache with local disk backend for Linux, macOS, and Windows

inputs:
  platform:
    description: "Platform: linux, macos, or windows"
    required: true

runs:
  using: composite
  steps:
    # Install sccache
    - name: Install sccache (Linux)
      if: inputs.platform == 'linux'
      shell: bash
      run: |
        # Detect architecture
        ARCH=$(uname -m)
        if [[ "$ARCH" == "x86_64" ]]; then
          SCCACHE_ARCH="x86_64-unknown-linux-musl"
        elif [[ "$ARCH" == "aarch64" ]]; then
          SCCACHE_ARCH="aarch64-unknown-linux-musl"
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi

        echo "Installing sccache for $ARCH ($SCCACHE_ARCH)"
        curl -L https://github.com/mozilla/sccache/releases/download/v0.7.4/sccache-v0.7.4-${SCCACHE_ARCH}.tar.gz | tar xz

        # Try with sudo if available, otherwise install directly (for containers running as root)
        if command -v sudo &> /dev/null; then
          sudo mv sccache-v0.7.4-${SCCACHE_ARCH}/sccache /usr/local/bin/
          sudo chmod +x /usr/local/bin/sccache
        else
          mv sccache-v0.7.4-${SCCACHE_ARCH}/sccache /usr/local/bin/
          chmod +x /usr/local/bin/sccache
        fi

        sccache --version

    - name: Install sccache (macOS)
      if: inputs.platform == 'macos'
      shell: bash
      run: |
        brew install sccache
        sccache --version

    - name: Install sccache (Windows)
      if: inputs.platform == 'windows'
      shell: bash
      run: |
        # Check if already installed
        if command -v sccache &> /dev/null; then
          echo "✅ sccache already installed: $(sccache --version)"
        else
          echo "Installing sccache for Windows..."
          install_dir="${RUNNER_TEMP}/sccache-bin"
          mkdir -p "$install_dir"
          curl -L -o "${RUNNER_TEMP}/sccache.tar.gz" https://github.com/mozilla/sccache/releases/download/v0.7.4/sccache-v0.7.4-x86_64-pc-windows-msvc.tar.gz
          cd "${RUNNER_TEMP}" && tar xzf sccache.tar.gz
          mv sccache-v0.7.4-x86_64-pc-windows-msvc/sccache.exe "$install_dir/sccache.exe"
          echo "$install_dir" >> "$GITHUB_PATH"
          export PATH="$install_dir:$PATH"
          sccache --version
        fi

    # Configure sccache with local disk backend
    - name: Configure sccache
      shell: bash
      run: |
        echo "SCCACHE_CACHE_ZSTD_LEVEL=3" >> $GITHUB_ENV
        echo "SCCACHE_IGNORE_SERVER_IO_ERROR=1" >> $GITHUB_ENV
        echo "SCCACHE_IDLE_TIMEOUT=0" >> $GITHUB_ENV
        echo "SCCACHE_BASE_DIR=$PWD" >> $GITHUB_ENV
        echo "SCCACHE_CACHE_SIZE=2G" >> $GITHUB_ENV

        # Set platform-specific cache directory
        if [[ "${{ inputs.platform }}" == "windows" ]]; then
          SCCACHE_DIR="C:/sccache"
        else
          SCCACHE_DIR="/tmp/.cache/sccache"
        fi
        mkdir -p "$SCCACHE_DIR"
        echo "SCCACHE_DIR=$SCCACHE_DIR" >> $GITHUB_ENV
        echo "sccache_cache_dir=$SCCACHE_DIR" >> $GITHUB_ENV

        # Get sccache path for CMake
        sccache_path=$(which sccache)
        echo "sccache_path=$sccache_path" >> $GITHUB_ENV

        echo "🔧 sccache configured for local disk backend"
