name: Check Formatting (comment /format to auto-fix)

on:
  pull_request:
    branches: [master]
  merge_group:
    types: [checks_requested]
jobs:
  check-formatting:
    if: false  # Temporarily disabled for Linux parallelism testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/format-setup
      - run: ./extras/formatting.sh --check-only
