name: Coverage (Nightly)

on:
  workflow_dispatch:
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  coverage:
    uses: ./.github/workflows/ci-slang-build.yml
    with:
      os: linux
      compiler: clang
      platform: x86_64
      config: debug
      runs-on: '["ubuntu-22.04"]'
      build-llvm: true
      enable-coverage: true
      coverage-deploy-pages: true
